### ISSUE TITLE
Cluster Update Example

### ISSUE THREAD

**Issue by yks0000** [googleapis/python-container#104]
Hi,

Is there an example to use Python `container_v1` api to update cluster to use stable `release_channel`. Currently we are not using release channel. I am trying to explore GCP GKE Python SDK and need help with this. 

I see `update_cluster` method needs `request` arg which is of type `container_v1.types.cluster_service.UpdateClusterRequest` which further need `update` of type `container_v1.types.ClusterUpdate`

When I am passing 

```
request = container_v1.types.cluster_service.UpdateClusterRequest(
                    name=cluster['name'],
                 update=container_v1.types.ClusterUpdate(desired_release_channel=container_v1.ReleaseChannel.Channel.STABLE))
                )
```

I am getting an error that 

`TypeError: Parameter to MergeFrom() must be instance of same class: expected google.container.v1.ReleaseChannel got Channel.
`.

I don't see an option to set STABLE release channel with ReleaseChannel

Please suggest.

**Comment by yks0000** [comment]
Below code worked

```python
update_request = container_v1.types.cluster_service.UpdateClusterRequest()
cluster_update = container_v1.types.ClusterUpdate()

desired_release_channel = container_v1.types.ReleaseChannel()
desired_release_channel.channel = container_v1.types.ReleaseChannel.Channel.STABLE

cluster_update.desired_release_channel = desired_release_channel

update_request.name = f"projects/{self.project_id}/locations/{cluster['location']}/clusters/{cluster['name']}"
update_request.update = cluster_update

# request = request_type()
cluster_operation = self.gke_client.update_cluster(request=update_request)
```

**Comment by yks0000** [comment]
Is there any better way of doing this?

**Comment by bourgeoisor** [comment]
@yks0000 The code snippet you have looks good. Do you have any question or concern in particular about it?

**Comment by yks0000** [comment]
All good @bourgeoisor. Closing this.
