### ISSUE TITLE
Types are only available at runtime

### ISSUE THREAD

**Issue by edigaryev** [googleapis/python-container#12]
When developing software using GKE API in IDE's like PyCharm, the editor won't provide any name hints as the [Types for Google Container Engine API Client](https://googleapis.dev/python/container/latest/gapic/v1/types.html) are generated at runtime:

https://github.com/googleapis/python-container/blob/6afc050f21c57a2d0eda3327c07510f2226aa6a6/google/cloud/container_v1/types.py#L34-L42

It'd be nice for these types to be pre-generated for IDE static analyzer to work, which will in turn enable hints and varios checks that greatly simplify the development process.

**Comment by busunkim96** [comment]
Unfortunately this is a limitation of our current library generator.

We are moving all our libraries to a new generator in the next 3-4 months, and the experience should be much better at that point.

Thanks for taking the time to file feedback!

**Comment by busunkim96** [comment]
This should now be resolved. The library types have their own docstrings: https://github.com/googleapis/python-container/blob/74a4ec1a99d5fcd74bafeab6939da337674c4fa5/google/cloud/container_v1/types/cluster_service.py#L372-L386

Please do let us know if the docstrings aren't showing up the way you expect in IDEs though. :)
