### ISSUE TITLE
Invalid constructor input for SetNodePoolSizeRequest: xxx

### ISSUE THREAD

**Issue by zt-oc** [googleapis/python-container#135]
Hello, 

I want to resize a cluster, so, I find of course this function "set_node_pool_size" but no where to add number of nodes in parameters:

What I tried: 

cluster_manager_client.set_node_pool_size(3)

``` def set_node_pool_size(
        self,
        request: cluster_service.SetNodePoolSizeRequest = None,
        *,
        retry: retries.Retry = gapic_v1.method.DEFAULT,
        timeout: float = None,
        metadata: Sequence[Tuple[str, str]] = (),
    ) -> cluster_service.Operation:
        r"""Sets the size for a specific node pool.```

**Comment by NimJay** [comment]
Hi there! :)

Have you tried passing a [`SetNodePoolSizeRequest`](https://googleapis.dev/python/container/latest/container_v1/types.html#google.cloud.container_v1.types.SetNodePoolSizeRequest) object into the `set_node_pool_size` method?
The `SetNodePoolSizeRequest` class has a [`node_count`](https://googleapis.dev/python/container/latest/container_v1/types.html#google.cloud.container_v1.types.SetNodePoolSizeRequest.node_count) property that you can set.

Let me know if this doesn't help.

**Comment by NimJay** [comment]
Just to provide some clarification...
Here's how I got the `set_node_pool_size` method working for me:

```python
from google.cloud import container_v1
from google.cloud.container_v1.types.cluster_service import SetNodePoolSizeRequest

PROJECT_ID = "my-project" # Change this.
ZONE = "us-central1-c" # Change this.
CLUSTER_NAME = "test-cluster" # Change this.
NODE_POOL_NAME = "default-pool" # Change this.

name = ("projects/" + PROJECT_ID 
    + "/locations/" + ZONE 
    + "/clusters/" + CLUSTER_NAME
    + "/nodePools/" + NODE_POOL_NAME)

client = container_v1.ClusterManagerClient()
request = SetNodePoolSizeRequest(name=name, node_count=3) # Set node_count to the number you desire.
client.set_node_pool_size(request)
```

In case you're wondering, you can learn about authentication [here](https://googleapis.dev/python/google-api-core/latest/auth.html).

**Comment by zt-oc** [comment]
But how?

request = google.cloud.container_v1.types.cluster_service.SetNodePoolSizeRequest(ClusterName=cluster_id,NodeCount=0,NodePoolName=nodePoolID)
cluster.set_node_pool_size(request)

Unfortunally there is not enought examples. Even if I tried this code:

 client.set_node_pool_size(projectID, zone, clusterID, nodePoolID, 3)

**Comment by zt-oc** [comment]
NimJay , thank you so much for your time and for the link about authentification.
I am using Google for 6 months now, many thinks to learn. 

I am using cloud function + cloud scheduler to resize cluster.

**Comment by NimJay** [comment]
@zt-oc, I'm going to close this issue as I believe the initial problem with `set_node_pool_size` has been resolved.
Let me know if you run into other issues with the `python-container` API. :)
