### ISSUE TITLE
Missing ability to set taints, tags and labels of nodepool

### ISSUE THREAD

**Issue by samos123** [googleapis/python-container#140]
GKE container NodePool update API supports updating the taints however looks like this python library does not support this yet.

See here for more info: https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters.nodePools/update

The `set_labels` function that exists is for applying them at a cluster level, however we need them at the nodepool level.

**Comment by rashisht1** [comment]
Additionally, the ability to updated `labels`, `tags` and `gvnic` is also missing in the python library.

**Comment by bourgeoisor** [comment]
Looks like the [proto](https://github.com/googleapis/googleapis/blob/master/google/container/v1beta1/cluster_service.proto#L2017) hasn't been updated yet. Investigating.

**Comment by bourgeoisor** [comment]
I can confirm there is some discrepancy internally, thank you for bringing this up! I will update this issue once it is fixed.

**Comment by bourgeoisor** [comment]
The upstream proto has been updated with `taints`, `tags`, `labels`, `gvnic`: https://github.com/googleapis/googleapis/blob/master/google/container/v1beta1/cluster_service.proto#L2196-L2209

Waiting for this PR to go through: https://github.com/googleapis/python-container/pull/147
