### ISSUE TITLE
Container: Cannot connect to regional cluster

### ISSUE THREAD

**Issue by mholleville** [googleapis/python-container#2]
Hi ! I can't get node pool list from regional cluster. Can you explain me why ?

Trying this

`client.list_node_pools(project_id=self.projectId, zone='europe-west1', cluster_id=self.clusterName)`

When I look documentation 

> zone (str): Deprecated. The name of the Google Compute Engine
                `zone <https://cloud.google.com/compute/docs/zones#available>`__ in
                which the cluster resides. This field has been deprecated and replaced
                by the parent field.

Trying using `parent` but `zone` is missing ...

But how can I get all node pool from regional cluster ? Is it a bug ?

**Comment by askmeegs** [comment]
> @mholleville - I think there might have been a typo in the comment above (slash before `projects`), this works for me with both a regional and zonal cluster:
> 
> ```python
> parent = 'projects/{}/locations/{}/clusters/{}'.format(project_id, location, cluster_id)
> print (client.list_node_pools(parent=parent, project_id=None, zone=None, cluster_id=None))
> ```

Following up on this issue - dijitali@'s example is working for me, `google_cloud_container 2.4.0`, with `us-central1` set as the `location` -- 

```
from google.cloud.container_v1.services.cluster_manager import ClusterManagerClient
from google.cloud.container_v1.types import cluster_service
import google.auth

credentials, project_id = google.auth.default()
location = "us-central1"
cluster_id="regional-cluster"

client = ClusterManagerClient(credentials=credentials)

parent = 'projects/{}/locations/{}/clusters/{}'.format(project_id, location, cluster_id)
print (client.list_node_pools(parent=parent, project_id=None, zone=None, cluster_id=None))
```

Output: 

```
node_pools {
  name: "default-pool"
  config {
    machine_type: "e2-medium"
...
```

Closing this issue given that there's a suitable workaround for the deprecated fields.
