### ISSUE TITLE
cannot import name 'cygrpc' from 'grpc._cython' (/opt/python/grpc/_cython/__init__.py)

### ISSUE THREAD

**Issue by venomwaqar** [googleapis/python-container#20]
I am trying to use the plugin `google-cloud-container` in AWS lambda, but I am having the following issue.
`cannot import name 'cygrpc' from 'grpc._cython' (/opt/python/grpc/_cython/__init__.py)`

I have tried installing the grpcio explicitly and with some versions but still having the same issue.

python version: 3.7
google-cloud-container version: 0.5.0

**Comment by JuanCamiloCast** [comment]
@venomwaqar hi,¿how did you solve this problem? thanks

**Comment by venomwaqar** [comment]
@JuanCamiloCast I don't know if its gonna fix your issue too, but I created a layer using Amazon Linux 2 (AMI) and Python 3.6 to install these dependencies and it worked.
At that time, for some reason, Python 3.6+ version was not working with AWS Lambda.

**Comment by JuanCamiloCast** [comment]
@venomwaqar thanks, i was using python 3.7. i already solved it.👍👌

**Comment by rahman17449** [comment]
@JuanCamiloCast I am using python 3.8 but still facing the issue. Please help!

**Comment by manu2504** [comment]
Problem seems to be inherent to grpc, not GCP. I was trying to use grpc framework in a python project and followed steps below to fix it.

Make sure to build the dependencies in a docker container mimicking the OS your lambda runtime runs in 

It worked for me (I'm using python3.8 runtime) after installing grpc dependencies on jdukewich/amazonlinux2-python3.8:latest docker image, zipping them on the container, then copying the zipped file locally and uploading it to lambda. You may certainly automatize the flow if you like.

**Comment by karthik2215** [comment]
I got same issue 

I am work on aws lambda function, i install the package but i got this type of error("Unable to import module 'lambda_function': cannot import name 'cygrpc' from 'grpc._cython' (/var/task/grpc/_cython/init.py)"). How to solve this type of error please suggest your ideas

**Comment by saimjamilSJ** [comment]
@karthik2215 i am getting the same error. how did u solve this problem?

**Comment by karthik2215** [comment]
@saimjamilSJ  That issue is nothing on my side, First of all i have already installed the all packages done in my local virtual environment. But i have one mistake on my side (i.e). i have manual upload the my project with venv on aws lamda function. But i have try it the visual studio command to connect aws serverless in my local system, That issue is solved for me 

Incase you check your packages list, you have not install cython package try this command to solve 

!pip install Cython

**Comment by pipipengn** [comment]
Tried adding this library using Lambda layer for python 3.8, still facing this issue.

**Comment by david-startinvest** [comment]
Having the same problem and tried all the solutions provided so far (6/1/2022) and still get the same error. Can anyone please help ?

**Comment by roshanlabh** [comment]
`cannot import name 'cygrpc' from 'grpc._cython' (/opt/python/grpc/_cython/__init__.py)`

If you are still facing the same issue with AWS Lambda layer and using mac for building the package locally. 
Then the solution is to just use linux (ubuntu) to build your `google-cloud-*` package. It will solve the issue.

**Comment by MartinUQ** [comment]
Did it on linux instead of mac and worked
