### ISSUE TITLE
`master_auth` in list_cluster response, is missing username and password.

### ISSUE THREAD

**Issue by venomwaqar** [googleapis/python-container#21]
I have enabled Basic Authentication in a given cluster, but in `list_cluster`, both of the username and password fields are missing. Although I can see If I use the `gcloud` cli.

Please let me know how can I view the Basic Authentication credentials using `google-cloud-container` library.

```
from google.oauth2 import service_account
from google.cloud import container_v1

credentials = service_account.Credentials.from_service_account_file(
            "/tmp/.key",
            scopes=["https://www.googleapis.com/auth/cloud-platform"],
    )
    
computeAPI = container_v1.ClusterManagerClient(credentials=credentials)
clusters_list = get_clusters_list(containerAPI, event['projectId'])
    for cluster in clusters_list:
       print("master_auth: ", cluster.master_auth)
       print("password: ", cluster.master_auth.password)
       print("username: ", cluster.master_auth.username)

def get_clusters_list(containerAPI, project):
    clusters_list = []
    request = containerAPI.list_clusters(parent="projects/{}/locations/-".format(project))
    if request != None and hasattr(request, 'clusters'):
        clusters_list.extend(request.clusters)
    return clusters_list
```
**OUTPUT**

> master_auth:  cluster_ca_certificate: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lRTW94N01sc3hRalVEMXZwOHp6K09TekFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRd01qWmpaalk0WXkwd01URm1MVFE0TW1FdFlqWTVaaTFrTldVMU9UYzBORGd6TVRBdwpIaGNOTWpBd05USXhNVGN4TURBMFdoY05NalV3TlRJd01UZ3hNREEwV2pBdk1TMHdLd1lEVlFRREV5UXdNalpqClpqWTRZeTB3TVRGbUxUUTRNbUV0WWpZNVppMWtOV1UxT1RjME5EZ3pNVEF3Z2dFaU1BMEdDU3FHU0...."
> password:  
> username:

P.S
I am running this code on AWS Lambda.

python version: 3.7
google-cloud-container version: 0.5.0
OS: Amazon Linux
AWS AMI: amzn2-ami-hvm-2.0.20200406.0-x86_64-gp2

**Comment by busunkim96** [comment]
Hi @venomwaqar,

It looks like you can use the `set_master_auth` method.

https://googleapis.dev/python/container/latest/gapic/v1/api.html?highlight=set_master_auth#google.cloud.container_v1.ClusterManagerClient.set_master_auth

**Comment by venomwaqar** [comment]
@busunkim96 I need to view the credentials that are already set, please review my comment again.

**Comment by busunkim96** [comment]
Apologies, I misread your question. 😄

Those fields should be available on the cluster object. `cluster.master_auth.password` and `cluster.master_auth.username`

Unless you're saying you can access those fields, but they appear to be empty?

**Comment by venomwaqar** [comment]
@busunkim96 thanks for re-opening this issue.

Those fields doesn't exists in the `cluster.master_auth` object. Although, when I use `gcloud` cli to cross-check, I can see that username and password do exists.

**Comment by busunkim96** [comment]
I was able to successfully get both the password and username. Can you try running this code in a clean virtual environment with the latest version of the library?

```
python3 -m venv env
source env/bin/activate
python3 -m pip install google-cloud-container
```



```py
from google.cloud import container_v1

client = container_v1.ClusterManagerClient()

PROJECT_ID="my-project"
ZONE="us-central1-a"

response = client.list_clusters(project_id=PROJECT_ID, zone=ZONE)
cluster = response.clusters[0]

# Get master auth password and username
print("password: ", cluster.master_auth.password)
print("username: ", cluster.master_auth.username)
```

**Comment by venomwaqar** [comment]
@busunkim96 sorry my bad, I have updated my ticket. Please can you review :-)

**Comment by 8032** [comment]
@busunkim96 continuing the discussion here as #47 was closed as a duplicate.
We have been in touch with GCP Support to seek to expedite the update the the client libraries, however they have advised that it will take some time to implement and there is no ETA for a fix for the client libraries and that the Google Client Libraries Team is working on this issue.

Can you advise when you expect the client libraries will be updated? And what the on going cadence will be for updates to client libraries for the release level of services?

**Comment by busunkim96** [comment]
The v1 surface has been updated (see https://github.com/googleapis/python-container/blob/master/CHANGELOG.md#220-2020-11-17 for a full list of changes).

A similar update is coming for v1beta1.
