### ISSUE TITLE
Unable to import module 'index': cannot import name 'cygrpc' from 'grpc._cython' 

### ISSUE THREAD

**Issue by pipipengn** [googleapis/python-container#255]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

When we installed the google-ads library, trying importing the cygrpc library, but getting the error as above.
I am using python 3.8.

**Comment by charlieyu1996** [comment]
Hi, may I ask for more information on this issue? Were you installing them in virtualenv? It would be helpful to list out the steps completed to reach this error message.

**Comment by pipipengn** [comment]
I had this problem while using AWS Lambda. It seems that AWS Lambda does not recognize the python library written in c++. I have solved this problem by uploading docker image to Lambda.
