### ISSUE TITLE
Documentation missing for the 2.0.0 release. 

### ISSUE THREAD

**Issue by aakarshg** [googleapis/python-container#38]
It's been a week since the 2.0.0 release, but the documentation still points to the [1.0.1 release as latest](https://googleapis.dev/python/container/latest/index.html#). This has caused a few issues with dependencies as certain functions seem to be deprecated in the 2.0.0, and calls being changed however missing documentation means there's no way to figure out the changes required.

**Comment by aakarshg** [comment]
Another issue is that the release commit includes update to changelog - https://github.com/googleapis/python-container/commit/98b440de15cb49e855d2244a8c3f6376dc94618b but doesn't quite mention the deprecated calls.

**Comment by busunkim96** [comment]
Hi @aakarshg, it looks like I missed updating the changelog with the methods that have been removed. I'll open a PR to list the removed methods in the changelog.

As for the docs, we had a bug in our pipeline that is being resolved. The docs should be up sometime tomorrow.

**Comment by busunkim96** [comment]
The [migration guide](https://github.com/googleapis/python-container/blob/master/UPGRADING.md) explains how to modify your code.

Please feel free to open another issue if you have questions or run into problems. Thanks!
