### ISSUE TITLE
Values for `name` field are supplied inconsistently across different types

### ISSUE THREAD

**Issue by lhriley** [googleapis/python-container#407]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-container/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: `Linux Mint 21.1 Vera`
  - Python version: `python --version` `Python 3.10.12`
  - pip version: `pip --version` `pip 23.1.2`
  - `google-cloud-container` version: `pip show google-cloud-container` `2.29.0`

#### Steps to reproduce

Compare the instructions and code related to how the `client` expects the `name` field to be supplied, and the value of the `name` field supplied by different `types`:

Example:

The client seems to consistently expect `name` to be provided in the same format:
`client.get_cluster()`:

https://github.com/googleapis/python-container/blob/c5806de9c61b1c9855f1c9a5c3fac1ea343e1acc/google/cloud/container_v1/services/cluster_manager/client.py#L642-L649

https://github.com/googleapis/python-container/blob/c5806de9c61b1c9855f1c9a5c3fac1ea343e1acc/google/cloud/container_v1/services/cluster_manager/client.py#L691-L695

`client.get_operation()`:

https://github.com/googleapis/python-container/blob/c5806de9c61b1c9855f1c9a5c3fac1ea343e1acc/google/cloud/container_v1/services/cluster_manager/client.py#L2426-L2433

https://github.com/googleapis/python-container/blob/c5806de9c61b1c9855f1c9a5c3fac1ea343e1acc/google/cloud/container_v1/services/cluster_manager/client.py#L2479-L2483

The types are inconsistent in how they provide the `name` field:

`Cluster(proto.Message)`:

https://github.com/googleapis/python-container/blob/c5806de9c61b1c9855f1c9a5c3fac1ea343e1acc/google/cloud/container_v1/types/cluster_service.py#L2349-L2356

`NodePool(proto.Message):

https://github.com/googleapis/python-container/blob/c5806de9c61b1c9855f1c9a5c3fac1ea343e1acc/google/cloud/container_v1/types/cluster_service.py#L5479-L5480

`Operation(proto.Message)`:

https://github.com/googleapis/python-container/blob/c5806de9c61b1c9855f1c9a5c3fac1ea343e1acc/google/cloud/container_v1/types/cluster_service.py#L3665-L3666

Some types such as `NodeConfig(proto.Message)` do not contain a `name` field at all:

https://github.com/googleapis/python-container/blob/c5806de9c61b1c9855f1c9a5c3fac1ea343e1acc/google/cloud/container_v1/types/cluster_service.py#L473C7-L474C1

However, in the case of the `client`, the actual expectation for `name` is to provide the URL path of the `self_link` which _is_ consistent across types that provide it:

https://github.com/googleapis/python-container/blob/c5806de9c61b1c9855f1c9a5c3fac1ea343e1acc/google/cloud/container_v1/types/cluster_service.py#L2540-L2541

https://github.com/googleapis/python-container/blob/c5806de9c61b1c9855f1c9a5c3fac1ea343e1acc/google/cloud/container_v1/types/cluster_service.py#L5504-L5505

#### Code example

Workaround is to use a function that removes the URL prefix that is _not_ considered part of `name` to the `client`:
```python
    def get_resource_name(self, cluster: container_v1.Cluster) -> str:
        return cluster.self_link.removeprefix("https://container.googleapis.com/v1/")
```

```python

from google.cloud import container_v1

"""
name (str):
    The name (project, location, cluster) of the cluster to
    retrieve. Specified in the format
    ``projects/*/locations/*/clusters/*``.

    This corresponds to the ``name`` field
    on the ``request`` instance; if ``request`` is provided, this
    should not be set.
"""

def good() -> container_v1.Operation:
    client = container_v1.ClusterManagerClient()

    cluster = client.get_cluster(name="projects/MYPROJECT/region/us-central1/clusters/MYCLUSTER")

    print(cluster.name)
    print(cluster.self_link)

    cluster_update = container_v1.ClusterUpdate()

    cluster_name = cluster.self_link.removeprefix("https://container.googleapis.com/v1/")

    cluster_update.desired_master_version = "1.26.5-gke.2700"

    request = container_v1.UpdateClusterRequest(
        name=cluster_name,
        update=cluster_update,
    )

    response = client.update_cluster(request=request)

    return response


def bad() -> container_v1.Operation:
    client = container_v1.ClusterManagerClient()

    cluster = client.get_cluster(name="projects/MYPROJECT/region/us-central1/clusters/MYCLUSTER")

    print(cluster.name)
    print(cluster.self_link)

    cluster_update = container_v1.ClusterUpdate()

    cluster_update.desired_master_version = "1.26.5-gke.2700"

    request = container_v1.UpdateClusterRequest(
        name=cluster.name,
        update=cluster_update,
    )

    response = client.update_cluster(request=request)

    return response


if __name__ == "__main__":
    print(good())
    print(bad())
```

#### Stack trace
```
google.api_core.exceptions.InvalidArgument: 400 Location "" does not exist. [request_id: "0x9afd14bb45b99ec6"]
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by parthea** [comment]
Hi @lhriley,

I was able to run the sample code without using [cluster.self_link](https://github.com/googleapis/python-container/blob/c5806de9c61b1c9855f1c9a5c3fac1ea343e1acc/google/cloud/container_v1/types/cluster_service.py#L2540C1-L2541). As you indicated, there is some tweaking needed if you want to try to use the value for the field `self_link` for other fields such as `name`. To run the sample without using `cluster.self_link` use the code below.

```
from google.cloud import container_v1
project = # Your Project
location = # Your location eg. "us-central1-b"
cluster = # name of the cluster

def sample_update_cluster():
    # Create a client
    client = container_v1.ClusterManagerClient()

    cluster_update = container_v1.ClusterUpdate(desired_master_version = "1.26.6-gke.1700")
    # Initialize request argument(s)
    request = container_v1.UpdateClusterRequest(
        name=f"projects/{project}/locations/{location}/clusters/{cluster}",
        update=cluster_update,
    )

    # Make the request
    response = client.update_cluster(request=request)

    # Handle the response
    print(response)

sample_update_cluster()
```


`NodeConfig` doesn't have the `name` field but this doesn't appear to be added as this class is used in `Cluster` and `NodePool` which do have a `name` field.

https://github.com/googleapis/python-container/blob/d9750ffecffacfd9051f6d3575c820e9f564261c/google/cloud/container_v1/types/cluster_service.py#L475-L476

https://github.com/googleapis/python-container/blob/d9750ffecffacfd9051f6d3575c820e9f564261c/google/cloud/container_v1/types/cluster_service.py#L2346-L2375

https://github.com/googleapis/python-container/blob/d9750ffecffacfd9051f6d3575c820e9f564261c/google/cloud/container_v1/types/cluster_service.py#L5502-L5514

I'm going to close this issue but please open a new issue if you have additional questions
