### ISSUE TITLE
workload_metadata_config returns mode 3 for GKE_METADATA

### ISSUE THREAD

**Issue by 8032** [googleapis/python-container#47]
#### Environment details

  - OS type and version: MacOS
  - Python version: 3.8.2
  - pip version: pip 20.1.1
  - `google-cloud-container` version: 2.1.0

#### Steps to reproduce

  1. Query GKE cluster with `GKE_METADATA` enabled and specify the region and project_id

```
from google.cloud.container_v1beta1.services.cluster_manager import ClusterManagerClient
from google.cloud.container_v1beta1.types.cluster_service import WorkloadMetadataConfig

client = ClusterManagerClient()
request = {"parent": f"projects/{project_id}/locations/{region}"}
clusters = client.list_clusters(request)
for cluster in clusters:
    for node in cluster.node_pools:
        mode = WorkloadMetadataConfig(node.config.workload_metadata_config)
        print(mode)

```

the mode value returned is 3 which is not present in the enum options in `from google.cloud.container_v1beta1.types.cluster_service import WorkloadMetadataConfig`

The documentation within the [client libraries](https://googleapis.dev/python/container/latest/container_v1beta1/types.html) does not provide sufficient detail on these enum values.

The code for the enum lookup in [python-container/google/cloud/container_v1beta1/types/cluster_service.py](https://github.com/googleapis/python-container/blob/master/google/cloud/container_v1beta1/types/cluster_service.py#L3185-L3205) does not have an enum for the value 3

The [REST API documentation for nodemetadata](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/NodeConfig#nodemetadata) suggests that this is the correct value.

**Comment by busunkim96** [comment]
Hi @8032 , This has the same issue as #21. The public-facing protos have not been updated for some time, so there are features that are not present in the generated libraries.

Googlers, see internal lissue 154160334.

If you have a support contract with google, please make sure to open a case. https://cloud.google.com/support

**Comment by 8032** [comment]
I have implemented a PR to update and am currently going through getting approval for the contributors agreement.
I had checked but missed that #21 is also related to this specific issue.

**Comment by busunkim96** [comment]
Hi @8032, I just pinged the service team for an ETA. I'll let you know when I get a response.
