### ISSUE TITLE
Python method for `gcloud container clusters get-credentials`

### ISSUE THREAD

**Issue by zcain117** [googleapis/python-container#6]
I need a Python client library method equivalent to [`gcloud container clusters get-credentials`](https://cloud.google.com/sdk/gcloud/reference/container/clusters/get-credentials) so I can query for Kubernetes Job status from a Google Cloud Function in Python.

As far as I can tell, `get-credentials` makes a GET request for a cluster and then applies some magic to turn the response into a kubeconfig file. I think I can make the same GET request in Python with [this method](https://googleapis.dev/python/container/latest/gapic/v1/api.html#google.cloud.container_v1.ClusterManagerClient.get_cluster), but I don't see any way to turn the response into a kubeconfig file.

Please let me know if I've overlooked something in the Python client library.

**Comment by busunkim96** [comment]
@ahmetb Do you know of someone with expertise with the Container (Kubernetes) API?

**Comment by ahmetb** [comment]
@zcain117 tl;dr you can't do this with a client library directly.

First of all, you can always figure out what API calls `gcloud` does by adding `--log-http`.

In this case it's simply doing a Get Cluster operation. https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.zones.clusters/get  and you've linked to it.

You **won't find a client library** turning the response into a `kubeconfig` file. That's something just `gcloud` does and you can imitate yourself sort of easily. 

Also you don't need a `kubeconfig` file to use `kubectl`. Run `kubectl options` to browse which options are available. In this case,

- use `--server` to point to a GKE master server (Get Cluster response has the url)
- use `--certificate-authority` to show the CA cert file (Get Cluster response has the base64 encoded string)

if you have GOOGLE_APPLICATION_CREDENTIALS env var set in the cluster, it should work.

You can find some tips at https://ahmet.im/blog/authenticating-to-gke-without-gcloud/.

**Comment by zcain117** [comment]
Thanks Ahmet! In our case, downloading service account credentials was not a secure option.

For anyone who comes across this issue, here is a solution that worked for us (and @ahmetb let me know if there's anything here that could be improved):
```
pip install kubernetes
pip install google-api-python-client
pip install google-cloud-container
```

```
from google.cloud import container_v1
import google.auth
import google.auth.transport.requests
from kubernetes import client as kubernetes_client
from tempfile import NamedTemporaryFile
import base64

def check_k8s_client():
    project_id = 'your-project-name'
    zone = 'us-central1-b'
    cluster_id = 'your-cluster-name'
    print('Attempting to init k8s client from cluster response.')
    container_client = container_v1.ClusterManagerClient()
    response = container_client.get_cluster(project_id, zone, cluster_id)
    credentials, project = google.auth.default(
        scopes=['https://www.googleapis.com/auth/cloud-platform'])
    creds, projects = google.auth.default()
    auth_req = google.auth.transport.requests.Request()
    creds.refresh(auth_req)
    configuration = kubernetes_client.Configuration()
    configuration.host = f'https://{response.endpoint}'
    with NamedTemporaryFile(delete=False) as ca_cert:
        ca_cert.write(
            base64.b64decode(response.master_auth.cluster_ca_certificate))
    configuration.ssl_ca_cert = ca_cert.name
    configuration.api_key_prefix['authorization'] = 'Bearer'
    configuration.api_key['authorization'] = creds.token

    k8s_client = kubernetes_client.BatchV1Api(
        kubernetes_client.ApiClient(configuration))
    ret = k8s_client.list_job_for_all_namespaces()
    print(ret)
check_k8s_client()
```

**Comment by ahmetb** [comment]
Yeah that should work. Make sure you are renewing the `Bearer` token every 3600s (or look at the expiration date on the refresh token).

**Comment by barath1997** [comment]
@zcain117 any idea how to do the same in golang? which libraries to import?

**Comment by zcain117** [comment]
no idea, sorry

**Comment by shakilbd009** [comment]
> @zcain117 any idea how to do the same in golang? which libraries to import?

i am having the same issue. did you make any progress with Go?

**Comment by barath1997** [comment]
> > @zcain117 any idea how to do the same in golang? which libraries to import?
> 
> i am having the same issue. did you make any progress with Go?

"https://kubernetes.io/docs/reference/access-authn-authz/authentication/#example-use-case"  u can check this for different authenticating mechanisms and pick which one is suitable for u" 

"cloud.google.com/go/container/apiv1"   use this library to create cluster client and with this client u can list clusters.

with the listed cluster details and authentication tokens u can create ur own kubeconfig file , using "gopkg.in/yaml.v2" library.

**Comment by shakilbd009** [comment]
and there you go!

https://bionic.fullstory.com/connect-to-google-kubernetes-with-gcp-credentials-and-pure-golang/

i think author because the title says with gcp- credendials thats why its not coming up in the google search. but its all about  how to connect to GKE cluster without kubeconfig file.

**Comment by tpdownes** [comment]
> Thanks Ahmet! In our case, downloading service account credentials was not a secure option.
> 
> For anyone who comes across this issue, here is a solution that worked for us (and @ahmetb let me know if there's anything here that could be improved):
> 
> ```
> pip install kubernetes
> pip install google-api-python-client
> pip install google-cloud-container
> ```
> 
> ```
> from google.cloud import container_v1
> import google.auth
> import google.auth.transport.requests
> from kubernetes import client as kubernetes_client
> from tempfile import NamedTemporaryFile
> import base64
> 
> def check_k8s_client():
>     project_id = 'your-project-name'
>     zone = 'us-central1-b'
>     cluster_id = 'your-cluster-name'
>     print('Attempting to init k8s client from cluster response.')
>     container_client = container_v1.ClusterManagerClient()
>     response = container_client.get_cluster(project_id, zone, cluster_id)
>     credentials, project = google.auth.default(
>         scopes=['https://www.googleapis.com/auth/cloud-platform'])
>     creds, projects = google.auth.default()
>     auth_req = google.auth.transport.requests.Request()
>     creds.refresh(auth_req)
>     configuration = kubernetes_client.Configuration()
>     configuration.host = f'https://{response.endpoint}'
>     with NamedTemporaryFile(delete=False) as ca_cert:
>         ca_cert.write(
>             base64.b64decode(response.master_auth.cluster_ca_certificate))
>     configuration.ssl_ca_cert = ca_cert.name
>     configuration.api_key_prefix['authorization'] = 'Bearer'
>     configuration.api_key['authorization'] = creds.token
> 
>     k8s_client = kubernetes_client.BatchV1Api(
>         kubernetes_client.ApiClient(configuration))
>     ret = k8s_client.list_job_for_all_namespaces()
>     print(ret)
> check_k8s_client()
> ```

For someone coming along in 2021+, the contemporary code would look like:

```python
def get_k8s_client(project_id: str, location: str,
                   cluster_id: str) -> kubernetes.client.CoreV1Api:
    container_client = google.cloud.container.ClusterManagerClient()
    request = {
        "name": f"projects/{project_id}/locations/{location}/clusters/{cluster_id}"
    }
    response = container_client.get_cluster(request=request)
    creds, projects = google.auth.default()
    auth_req = google.auth.transport.requests.Request()
    creds.refresh(auth_req)
    configuration = kubernetes.client.Configuration()
    configuration.host = f'https://{response.endpoint}'
    with NamedTemporaryFile(delete=False) as ca_cert:
        ca_cert.write(base64.b64decode(response.master_auth.cluster_ca_certificate))
        configuration.ssl_ca_cert = ca_cert.name
    configuration.api_key_prefix['authorization'] = 'Bearer'
    configuration.api_key['authorization'] = creds.token

    cli = kubernetes.client.CoreV1Api(kubernetes.client.ApiClient(configuration))
    custom_cli = kubernetes.client.CustomObjectsApi(
        kubernetes.client.ApiClient(configuration))
    return (cli, custom_cli)
```

**Comment by jaredtalon88** [comment]
Thanks! This worked for me once I added scopes like the original.

```
creds, projects = google.auth.default(scopes=['https://www.googleapis.com/auth/cloud-platform'])
```
